export const SET_LOADING = 'SET_LOADING'
export const SET_SNACK_MESSAGE = 'SET_SNACK_MESSAGE'

export const SET_LANG = 'SET_LANG'

export const SET_MODAL_IS_AUTH = 'SET_MODAL_IS_AUTH'
export const SET_MODAL_GAME_DESCRIPTION = 'SET_MODAL_GAME_DESCRIPTION'
export const SET_GAME_DESCRIPTION = 'SET_GAME_DESCRIPTION'
export const SET_MODAL_KEY = 'SET_MODAL_KEY'
export const SET_MODAL_AUTH = 'SET_MODAL_AUTH'
export const SET_MODAL_REGISTER = 'SET_MODAL_REGISTER'
export const SET_EDIT_PAGE = 'SET_EDIT_PAGE'
export const SET_MODAL_DRAW_WINNER = 'SET_MODAL_DRAW_WINNER'
export const SET_MODAL_GAME_DETAILS = 'SET_MODAL_GAME_DETAILS'
export const SET_VISIT_SITE_DETAILS = 'SET_VISIT_SITE_DETAILS'
export const CLICK_CHECK_WEBSITE = 'CLICK_CHECK_WEBSITE'
export const SET_MODAL_TWITTER_VIEW_POST = 'SET_MODAL_TWITTER_VIEW_POST'
export const EDIT_DRAW_WINNER = 'EDIT_DRAW_WINNER'

export const CREATE_TASK_ONE = 'CREATE_TASK_ONE'
export const CREATE_TASK_TWO = 'CREATE_TASK_TWO'
export const CREATE_TASK_THREE = 'CREATE_TASK_THREE'

export const ADD_GIFT = 'ADD_GIFT'
export const REMOVE_GIFT = 'REMOVE_GIFT'

export const EDIT_TASK_ONE = 'EDIT_TASK_ONE'
export const EDIT_TASK_TWO = 'EDIT_TASK_TWO'
export const EDIT_TASK_THREE = 'EDIT_TASK_THREE'

export const SET_HOME_PAGE = 'SET_HOME_PAGE'
export const GAME_DESC_NOTIFICATION = 'GAME_DESC_NOTIFICATION'
